{% set name = 'gatk-dict' %}
{% set version = "0.0.1" %}

package:
    name: nf-{{ name|lower }}
    version: {{ version }}
 
build:
    number: 0
    noarch: generic
    script: mkdir $PREFIX/nextflow && cp -R tools/{{ name | lower }} $PREFIX/nextflow

source:
    url:
        - https://github.com/grst/modules/archive/master.zip 

about: 
    home: https://github.com/nf-core/modules/
    license: MIT
    summary: create a dictionary file from a fasta file

extra: 
    keywords:
        - dictionary
    tools:
        - gatk:
            description: |
                The GATK toolkit offers a wide variety of tools with a primary focus on variant discovery and genotyping, developed in the Data Sciences Platform at the Broad Institute.
            homepage: https://gatk.broadinstitute.org/hc/en-us
            documentation: https://gatk.broadinstitute.org/hc/en-us/categories/360002369672s
            doi: 10.1158/1538-7445.AM2017-3590
    input:
        -
            - input:
                type: file
                description: Input fasta file
                pattern: "*.{fasta,fa}"
    output:
        -
            - dict:
                type: file
                description: gatk dictionary file
                pattern: "*.{fasta,fa}.{dict}"
    authors:
        - maxulysse