{% set name = 'trim_galore' %}
{% set version = "0.0.1" %}

package:
    name: {{ name|lower }}
    version: {{ version }}
 
build:
    number: 0
    noarch: generic
    script: mkdir $PREFIX/nextflow && cp -R tools/{{ name | lower }} $PREFIX/nextflow

source:
    url:
        - https://github.com/grst/modules/archive/master.zip 

about: 
    home: https://github.com/nf-core/modules/
    license: MIT
    summary: Trim FastQ files using Trim Galore!

extra: 
    keywords:
        - trimming
        - adapters
        - sequencing adapters
    tools:
        - fastqc:
            description: |
                A wrapper tool around Cutadapt and FastQC to consistently apply quality
                and adapter trimming to FastQ files, with some extra functionality for
                MspI-digested RRBS-type (Reduced Representation Bisufite-Seq) libraries.
            homepage: https://www.bioinformatics.babraham.ac.uk/projects/trim_galore/
            documentation: https://github.com/FelixKrueger/TrimGalore/blob/master/Docs/Trim_Galore_User_Guide.md
    input:
        -
            - sample_id:
                type: string
                description: Sample identifier
            - reads:
                type: file
                description: Input FastQ file, or pair of files
    output:
        -
            - sample_id:
                type: string
                description: Sample identifier
            - trimmed_fastq:
                type: file
                description: Trimmed FastQ files
                pattern: "*fq.gz"
        -
            - report:
                type: file
                description: Trim Galore! trimming report
                pattern: "*trimming_report.txt"
        -
            - fastqc_report:
                type: file
                description: FastQC report
                pattern: "*_fastqc.{zip,html}"
    authors:
        - ewels
        - grst
