## TODO nf-core: Please delete all of these TODO statements once the file has been curated
## TODO nf-core: Change the name of "software_tool" below
name: software_tool
## TODO nf-core: Add a description and keywords
description: Run FastQC on sequenced reads
keywords:
    - quality control
    - qc
    - adapters
    - fastq
tools:
    ## TODO nf-core: Change the name of "software" below
    - software:
        ## TODO nf-core: Add a description and other details for the software below
        description: |
            FastQC gives general quality metrics about your reads.
            It provides information about the quality score distribution
            across your reads, the per base sequence content (%A/C/G/T).
            You get information about adapter contamination and other
            overrepresented sequences.
        homepage: https://www.bioinformatics.babraham.ac.uk/projects/fastqc/
        documentation: https://www.bioinformatics.babraham.ac.uk/projects/fastqc/Help/
## TODO nf-core: If you are using any additional "params" in the main.nf script of the module add them below
params:
    - outdir:
        type: string
        description: |
            The pipeline's output directory. By default, the module will
            output files into `$params.outdir/<SOFTWARE>`
    - publish_dir_mode:
        type: string
        description: |
            Value for the Nextflow `publishDir` mode parameter.
            Available: symlink, rellink, link, copy, copyNoFollow, move.
    - enable_conda:
        type: boolean
        description: |
            Run the module with Conda using the software specified
            via the `conda` directive
## TODO nf-core: Add a description of all of the variables used as input
input:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - reads:
        type: file
        description: |
            List of input FastQ files of size 1 and 2 for single-end and paired-end data,
            respectively.
## TODO nf-core: Add a description of all of the variables used as output
output:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - html:
        type: file
        description: FastQC report
        pattern: "*_{fastqc.html}"
    - zip:
        type: file
        description: FastQC report archive
        pattern: "*_{fastqc.zip}"
    - version:
        type: file
        description: File containing software version
        pattern: "*.{version.txt}"
## TODO nf-core: Add your GitHub username below
authors:
    - "@your_github_username"
